kind: pipeline
name: default

steps:
- name: build
  image: archlinux/base
  commands:
    - mkdir build
    - chgrp nobody build
    - chmod g+ws build
    - setfacl -m u::rwx,g::rwx build
    - setfacl -d --set u::rwx,g::rwx,o::r build
    - ls
    - pacman -Sy --noconfirm binutils sudo grep fakeroot file
    - pacman -S --noconfirm libmpc gcc-ada doxygen lib32-glibc lib32-gcc-libs python git dejagnu inetutils patch base-devel neofetch
    - neofetch
    - mv PKGBUILD build/
    - mv c89 build/
    - mv c99 build/
    - mv fs64270.patch build/
    - mv gdc_artificial_decl.patch build/
    - mv gdc_phobos_path.patch build/
    - mv gdc_thunk_weak_ref.patch build/
    - pushd build
    - sudo -u nobody makepkg -c
    - ls -la
    - popd
    - mv build/gcc-* ./
    - mv build/PKGBUILD ./
- name: test
  image: archlinux/base
  commands:
    - pacman -Sy --noconfirm namcap grep
    - namcap PKGBUILD
    - namcap gcc-*